#!/usr/bin/with-contenv bash

s6-echo "Starting gunicorn"
cd /usr/src/paperless/src/
sudo -HEu paperless /usr/bin/gunicorn -c /usr/src/paperless/gunicorn.conf ${EXTRA_PARAMS} -b 0.0.0.0:8000 paperless.wsgi